name: chatappfirebase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  shared_preferences: ^2.2.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  firebase_storage: ^11.5.2
  intl: ^0.17.0
  fluttertoast: ^8.2.4
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Jalnan2TTF.ttf
      fonts:
        - asset: fonts/Jalnan2TTF.ttf
          weight: 700
